/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9-dev at Thu Apr 20 16:31:43 2017. */

#ifndef PB_BME280_PB_H_INCLUDED
#define PB_BME280_PB_H_INCLUDED
#include "pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _SensorData {
    int32_t sensorId;
    bool has_temperature;
    float temperature;
    bool has_humidity;
    float humidity;
    bool has_pressure;
    float pressure;
    bool has_altitude;
    float altitude;
/* @@protoc_insertion_point(struct:SensorData) */
} SensorData;

/* Default values for struct fields */

/* Initializer values for message structs */
#define SensorData_init_default                  {0, false, 0, false, 0, false, 0, false, 0}
#define SensorData_init_zero                     {0, false, 0, false, 0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define SensorData_sensorId_tag                  1
#define SensorData_temperature_tag               4
#define SensorData_humidity_tag                  5
#define SensorData_pressure_tag                  6
#define SensorData_altitude_tag                  7

/* Struct field encoding specification for nanopb */
extern const pb_field_t SensorData_fields[6];

/* Maximum encoded size of messages (where known) */
#define SensorData_size                          31

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define BME280_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
