/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9-dev at Thu Apr 20 16:13:50 2017. */

#include "temperature.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t SensorData_fields[3] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, SensorData, sensorId, sensorId, 0),
    PB_FIELD(  4, FLOAT   , OPTIONAL, STATIC  , OTHER, SensorData, temperature, sensorId, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
